//! Attachment variable-rate shading: per-frame-slot `R8_UINT` rate images
//! generated by a compute pass from the depth buffer.
//!
//! Each tile shades coarse (2×2) when its framebuffer block is entirely
//! far/sky and free of silhouette edges — see `shaders/vrs.comp.slang`. Because
//! the classifier reads depth, coarsening is orientation-correct and covers
//! distant terrain, not just sky: pitch down and near terrain keeps full rate.
//!
//! The compute pass reads *this slot's* depth from two cycles ago (its fence is
//! already waited at frame start), so no depth prepass or extra synchronisation
//! is needed. The pipeline/descriptors live in [`super::pipeline`]; the dispatch
//! and barriers are recorded by `Renderer::record_vrs_generate`.
//!
//! Only [`Vrs::new`] can mint a value, and it takes a [`FragmentShadingRate`]
//! capability proof, so holding a `Vrs` proves attachment VRS is enabled.

use ash::vk;

use super::alloc::find_memory_type;
use super::buffers::FRAMES_IN_FLIGHT;
use super::device::FragmentShadingRate;

const SLOTS: usize = FRAMES_IN_FLIGHT as usize;

/// Push constants for `vrs.comp`. `d_threshold`: reversed-Z depth below which a
/// tile counts as far/sky (see `Renderer::record_vrs_generate`). `texel_w/h`:
/// framebuffer pixels per tile.
#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
pub(crate) struct VrsPush {
    pub d_threshold: f32,
    pub texel_w: u32,
    pub texel_h: u32,
}

/// The value `cmd_begin_rendering` accepts to drive attachment VRS. Produced
/// only by `Renderer::record_vrs_generate`, which guarantees the referenced
/// image has been generated and transitioned to the attachment layout.
pub(crate) struct RateAttachment {
    pub view: vk::ImageView,
    pub texel_size: vk::Extent2D,
}

struct RateImage {
    image: vk::Image,
    memory: vk::DeviceMemory,
    view: vk::ImageView,
}

pub(crate) struct Vrs {
    /// Framebuffer block one rate texel covers (device's largest tile → the
    /// smallest, cheapest rate image). Single source of truth: shared by the
    /// image extent, the rendering attachment info, and the pipelines.
    pub texel_size: vk::Extent2D,
    /// Rate-image dimensions in texels (`ceil(render_extent / texel_size)`).
    tiles: vk::Extent2D,
    images: [RateImage; SLOTS],
}

impl Vrs {
    /// Minted only from the capability proof. `render_extent` is the (possibly
    /// scaled) offscreen resolution the rate image aligns to.
    pub fn new(
        device: &ash::Device,
        memory_props: &vk::PhysicalDeviceMemoryProperties,
        fsr: &FragmentShadingRate,
        render_extent: vk::Extent2D,
    ) -> Vrs {
        let texel_size = fsr.texel_size;
        let tiles = vk::Extent2D {
            width: render_extent.width.div_ceil(texel_size.width).max(1),
            height: render_extent.height.div_ceil(texel_size.height).max(1),
        };
        let images = std::array::from_fn(|_| create_rate_image(device, memory_props, tiles));
        Vrs {
            texel_size,
            tiles,
            images,
        }
    }

    pub fn tiles(&self) -> vk::Extent2D {
        self.tiles
    }

    pub fn view(&self, slot: usize) -> vk::ImageView {
        self.images[slot].view
    }

    pub fn image(&self, slot: usize) -> vk::Image {
        self.images[slot].image
    }

    pub unsafe fn destroy(&mut self, device: &ash::Device) {
        unsafe {
            for img in &self.images {
                device.destroy_image_view(img.view, None);
                device.destroy_image(img.image, None);
                device.free_memory(img.memory, None);
            }
        }
    }
}

fn create_rate_image(
    device: &ash::Device,
    memory_props: &vk::PhysicalDeviceMemoryProperties,
    tiles: vk::Extent2D,
) -> RateImage {
    let image_info = vk::ImageCreateInfo::default()
        .image_type(vk::ImageType::TYPE_2D)
        .format(vk::Format::R8_UINT)
        .extent(vk::Extent3D {
            width: tiles.width,
            height: tiles.height,
            depth: 1,
        })
        .mip_levels(1)
        .array_layers(1)
        .samples(vk::SampleCountFlags::TYPE_1)
        .tiling(vk::ImageTiling::OPTIMAL)
        // STORAGE: written by the compute classifier. FSR attachment: read by
        // the geometry pass as the rate map.
        .usage(
            vk::ImageUsageFlags::STORAGE
                | vk::ImageUsageFlags::FRAGMENT_SHADING_RATE_ATTACHMENT_KHR,
        )
        .sharing_mode(vk::SharingMode::EXCLUSIVE)
        .initial_layout(vk::ImageLayout::UNDEFINED);
    let image = unsafe {
        device
            .create_image(&image_info, None)
            .expect("Failed to create rate image")
    };
    let requirements = unsafe { device.get_image_memory_requirements(image) };
    let memory = unsafe {
        device
            .allocate_memory(
                &vk::MemoryAllocateInfo::default()
                    .allocation_size(requirements.size)
                    .memory_type_index(find_memory_type(
                        memory_props,
                        requirements.memory_type_bits,
                        vk::MemoryPropertyFlags::DEVICE_LOCAL,
                    )),
                None,
            )
            .expect("Failed to allocate rate image memory")
    };
    unsafe {
        device
            .bind_image_memory(image, memory, 0)
            .expect("Failed to bind rate image memory");
    }

    let subresource = vk::ImageSubresourceRange {
        aspect_mask: vk::ImageAspectFlags::COLOR,
        base_mip_level: 0,
        level_count: 1,
        base_array_layer: 0,
        layer_count: 1,
    };
    let view = unsafe {
        device
            .create_image_view(
                &vk::ImageViewCreateInfo::default()
                    .image(image)
                    .view_type(vk::ImageViewType::TYPE_2D)
                    .format(vk::Format::R8_UINT)
                    .subresource_range(subresource),
                None,
            )
            .expect("Failed to create rate image view")
    };

    RateImage {
        image,
        memory,
        view,
    }
}
